server {
    listen 80;
    server_name 13.239.116.166;

    location ^~ /.well-known/acme-challenge/ {
        root /home/ec2-user/borrowback/client/dist;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name 13.239.116.166;

    ssl_certificate /etc/letsencrypt/live/borrowback-ip/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/borrowback-ip/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /home/ec2-user/borrowback/client/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://localhost:5000/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
